os: linux
dist: xenial
language: python
python: 3.7
install:
  - pip install mkdocs mkdocs-material pymdown-extensions pygments mkdocs-table-reader-plugin==0.3.0
before_script:
  - cd mindsdb-docs
#build docs  
script: mkdocs build --verbose --clean 
# deploy to github pages
deploy:
    provider: pages
    strategy: git
    cleanup: true
    token: $GITHUB_TOKEN
    local_dir: site
    on:
      branch: master
      condition: $DEPLOYMENT_ENV = "true"
