site_name: MindsDB Documentation
repo_name: 'mindsdb/mindsdb'
repo_url: 'https://github.com/mindsdb/mindsdb'
theme:
  name: 'material'
  custom_dir: overrides
  logo: assets/mdb_logo_w.svg
  favicon: assets/mdb_logo.png
plugins:
    - search:
        lang: 'en'
        social:
          - type: 'github'
            link: 'https://github.com/mindsdb/mindsdb'
          - type: 'twitter'
            link: 'https://twitter.com/mindsdb'
          - type: 'link'
            link: 'https://www.mindsdb.com'
    - table-reader
markdown_extensions:
  - codehilite
  - admonition
nav:
  - Installing MindsDB: Installing.md
  - AutoML in Databases:
    - AI Tables: databases/index.md
    - AI Tables in MariaDB: databases/MariaDB.md
    - AI Tables in ClickHouse: databases/Clickhouse.md
  - AutoML from code:
    - Python native:
      - Starter Example: tutorials/BasicExample.md
      - Timeseries Data: tutorials/Timeseries.md
      - Running on Google Colab: GoogleColab.md
      - Running on Jupyter Notebook: JupyterNotebook.md
      - Predictor Interface: PredictorInterface.md
      - Functional Interface: FunctionalInterface.md
      - Advanced usecases: tutorials/AdvancedExamples.md
      - Data sources: features/DataSources.md
      - Configuration Settings: Config.md
      - MindsDB SDK: server/SDKs.md
      - Use Cases:
        - High-Tech & Manufacturing:
          - Predictive Maintenance: tutorials/PredictiveMaintenance.md
        - Financial Services:
          - Credit Scoring: tutorials/CreditScoring.md
        - Retail & Online:
          - Custiner Lifetime Value Optimization: tutorials/CustomerLifetimeValue.md
          - Fraud Detection: tutorials/FraudDetection.md
        - Health Care:
          - Patient Health: tutorials/PatientHealthOutcomes.md
          - Medical Diagnosis: tutorials/MedicalDiagnosis.md
        - Travel:
          - Hotel Booking Demand: tutorials/HotelBooking.md
        - Telecomunications:
          - Customer Churn Reduction: tutorials/ChurnReduction.md
  - AutoML building blocks: 
    - Introduction to Lightwood: lightwood/info.md
    - Predictor API: lightwood/API.md
  - AutoML Explainability:
    - MindsDB Scout:
      - Getting Started: scout/Introduction.md
      - Connection: scout/Connection.md
      - Datasources: scout/Datasources.md
      - Predictors: scout/Predictors.md
      - Query: scout/Query.md
  - Comparisons:
    - Comparison with other Libraries: comparisons/ComparsionWithOtherLibraries.md
  - Contributing:
    - FAQ: FAQ.md
    - Inside MindsDB: InsideMindsDB.md
google_analytics: ['UA-96178523-1', 'docs.mindsdb.com']
extra_css:
  - stylesheets/extra.css
